package review

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/ductone/orrey/internal/jev"
)

const sampleDiff = `diff --git a/internal/auth/token.go b/internal/auth/token.go
index 111..222 100644
--- a/internal/auth/token.go
+++ b/internal/auth/token.go
@@ -1,4 +1,5 @@
 package auth
-func Refresh() {}
+func Refresh() error { return nil }
+-- this added line starts with dashes
--- this removed line starts with dashes
diff --git a/docs/guide.md b/docs/guide.md
new file mode 100644
--- /dev/null
+++ b/docs/guide.md
@@ -0,0 +1,2 @@
+# Guide
+Some prose.
diff --git a/old.txt b/old.txt
deleted file mode 100644
--- a/old.txt
+++ /dev/null
@@ -1 +0,0 @@
-gone
diff --git a/a.go b/b.go
similarity index 90%
rename from a.go
rename to b.go
diff --git a/logo.png b/logo.png
Binary files a/logo.png and b/logo.png differ
`

func TestParseDiff(t *testing.T) {
	files := ParseDiff([]byte(sampleDiff))
	if len(files) != 5 {
		t.Fatalf("files = %d", len(files))
	}
	for i, want := range []struct {
		path    string
		status  Status
		added   int
		removed int
		binary  bool
	}{
		{"internal/auth/token.go", Modified, 2, 2, false},
		{"docs/guide.md", Added, 2, 0, false},
		{"old.txt", Deleted, 0, 1, false},
		{"b.go", Renamed, 0, 0, false},
		{"logo.png", Modified, 0, 0, true},
	} {
		f := files[i]
		if f.Path != want.path || f.Status != want.status || f.Added != want.added || f.Removed != want.removed || f.Binary != want.binary {
			t.Errorf("file %d = %+v, want %+v", i, f, want)
		}
	}
	if files[3].OldPath != "a.go" {
		t.Errorf("rename source = %q", files[3].OldPath)
	}
	if !strings.HasPrefix(files[0].Patch, "diff --git a/internal/auth/token.go") || strings.Contains(files[0].Patch, "docs/guide.md") {
		t.Errorf("patch boundaries wrong: %q", files[0].Patch)
	}
}

func TestParseDiffHarnessUntrackedFormat(t *testing.T) {
	diff := "\ndiff --git a/new.go b/new.go\nnew file mode 100644\n--- /dev/null\n+++ b/new.go\n@@ new file @@\n+package x\n+func A() {}\n\ndiff --git a/blob.bin b/blob.bin\nnew file mode 100644\n--- /dev/null\n+++ b/blob.bin\n@@ new file @@\n+[binary file omitted]\n"
	files := ParseDiff([]byte(diff))
	if len(files) != 2 || files[0].Status != Added || files[0].Added != 2 || !files[1].Binary {
		t.Fatalf("files = %+v", files)
	}
}

func TestParseDiffMarksTruncation(t *testing.T) {
	files := ParseDiff([]byte("diff --git a/x.go b/x.go\n--- a/x.go\n+++ b/x.go\n@@ -1 +1 @@\n+partial li"))
	if len(files) != 1 || !strings.Contains(files[0].Patch, "[diff truncated]") {
		t.Fatalf("files = %+v", files)
	}
	if ParseDiff(nil) != nil || len(ParseDiff([]byte("not a diff\n"))) != 0 {
		t.Fatal("input without sections yields no files")
	}
}

func TestClassify(t *testing.T) {
	for _, tc := range []struct {
		path, patch string
		binary      bool
		want        Class
	}{
		{"main.go", "", false, Code},
		{"web/app.tsx", "", false, Code},
		{"scripts/deploy.sh", "", false, Code},
		{"Makefile", "", false, Code},
		{"build/rules.mk", "", false, Generated},
		{"tools/rules.mk", "", false, Code},
		{"Dockerfile", "", false, Code},
		{"go.mod", "", false, Code},
		{"db/migrate.sql", "", false, Code},
		{"api/v1/service.proto", "", false, Code},
		{"README.md", "", false, Other},
		{"config/app.yaml", "", false, Other},
		{".github/workflows/ci.yml", "", false, Other},
		{"data/inventory.json", "", false, Other},
		{"logo.svg", "", false, Asset},
		{"img/Photo.PNG", "", false, Asset},
		{"fonts/x.woff2", "", false, Asset},
		{"package-lock.json", "", false, Lockfile},
		{"go.sum", "", false, Lockfile},
		{"web/pnpm-lock.yaml", "", false, Lockfile},
		{"api/v1/service.pb.go", "", false, Generated},
		{"py/svc_pb2.py", "", false, Generated},
		{"web/dist/app.js", "", false, Generated},
		{"vendor/x/y.go", "", false, Generated},
		{"app.min.js", "", false, Generated},
		{"x/zz_gen.go", "+// Code generated by stringer; DO NOT EDIT.\n+package x\n", false, Generated},
		{"x/plain.go", "+package x\n+// do not use this lightly\n", false, Code},
		{"blob.dat", "", true, BinaryC},
		{"main.go", "", true, BinaryC},
	} {
		f := File{Path: tc.path, Patch: tc.patch, Binary: tc.binary}
		Classify(&f)
		if f.Class != tc.want {
			t.Errorf("%s: class %s, want %s", tc.path, f.Class, tc.want)
		}
	}
}

// fakeClassifier answers from maps keyed by path or finding text.
type fakeClassifier struct {
	needs map[string]float64
	err   error
	calls atomic.Int32
}

func (f *fakeClassifier) NeedsReview(_ context.Context, _ string, files []File) ([]float64, error) {
	f.calls.Add(1)
	if f.err != nil {
		return nil, f.err
	}
	out := make([]float64, len(files))
	for i, file := range files {
		out[i] = f.needs[file.Path]
	}
	return out, nil
}

func file(path string, size int) File {
	return File{Path: path, Status: Modified, Added: 1, Patch: "diff --git a/" + path + " b/" + path + "\n" + strings.Repeat("+x\n", size/3)}
}

func decision(p Plan, path string) Decision {
	for _, d := range p.Decisions {
		if d.File.Path == path {
			return d
		}
	}
	return Decision{}
}

func TestBuildTriagesByClassAndClassifier(t *testing.T) {
	files := []File{file("Makefile", 300), file("docs/rfc.md", 3000), file("ci/pipeline.yaml", 600), file("logo.svg", 9000), file("package-lock.json", 9000), {Path: "notes.txt", Status: Deleted, Patch: "-x\n"}}
	c := &fakeClassifier{needs: map[string]float64{"docs/rfc.md": 0.05, "ci/pipeline.yaml": 0.8}}
	plan := Build(context.Background(), files, "task", c, Options{})
	if plan.Skip || len(plan.Shards) != 1 {
		t.Fatalf("plan = %+v", plan)
	}
	for path, included := range map[string]bool{"Makefile": true, "ci/pipeline.yaml": true, "docs/rfc.md": false, "logo.svg": false, "package-lock.json": false, "notes.txt": false} {
		if d := decision(plan, path); d.Included != included {
			t.Errorf("%s included=%v (%s)", path, d.Included, d.Reason)
		}
	}
	if d := decision(plan, "docs/rfc.md"); d.Score == nil || *d.Score != 0.05 || !strings.Contains(d.Reason, "0.05") {
		t.Errorf("docs decision = %+v", d)
	}
	// Code is never sent to the classifier.
	if c.calls.Load() != 1 {
		t.Errorf("classifier calls = %d", c.calls.Load())
	}
	if plan.Turns != baseTurns {
		t.Errorf("turns=%d", plan.Turns)
	}
	spec := plan.Spec(0)
	for _, want := range []string{"FILES IN THIS REVIEW", "- Makefile (modified, code", "ALSO CHANGED, NOT SHOWN", "logo.svg (modified, asset", "docs/rfc.md", "DIFF\ndiff --git a/Makefile"} {
		if !strings.Contains(spec, want) {
			t.Errorf("spec missing %q", want)
		}
	}
	if strings.Contains(spec, "part 1 of") {
		t.Error("a single-shard spec must not mention parts")
	}
}

func TestBuildWithoutClassifierReviewsEverythingNonTrivial(t *testing.T) {
	plan := Build(context.Background(), []File{file("docs/rfc.md", 300), file("logo.svg", 300)}, "task", nil, Options{})
	if !decision(plan, "docs/rfc.md").Included || decision(plan, "logo.svg").Included {
		t.Fatalf("plan = %+v", plan.Decisions)
	}
}

func TestBuildFallsBackWhenTheClassifierFails(t *testing.T) {
	c := &fakeClassifier{err: errors.New("jev: HTTP 529")}
	plan := Build(context.Background(), []File{file("docs/rfc.md", 300)}, "task", c, Options{})
	if !decision(plan, "docs/rfc.md").Included || !strings.Contains(plan.ClassifierError, "529") {
		t.Fatalf("plan = %+v", plan)
	}
}

func TestBuildSkipsWhenNothingNeedsReview(t *testing.T) {
	c := &fakeClassifier{needs: map[string]float64{"docs/a.md": 0.1}}
	plan := Build(context.Background(), []File{file("docs/a.md", 300), file("img/x.png", 300), file("go.sum", 300)}, "task", c, Options{})
	if !plan.Skip || !strings.Contains(plan.SkipReason, "3 changed files") || len(plan.Shards) != 0 {
		t.Fatalf("plan = %+v", plan)
	}
}

func TestBuildNeverSkipsCode(t *testing.T) {
	c := &fakeClassifier{}
	plan := Build(context.Background(), []File{file("main.go", 30)}, "task", c, Options{})
	if plan.Skip || len(plan.Shards) != 1 {
		t.Fatalf("plan = %+v", plan)
	}
}

func TestReviewSizing(t *testing.T) {
	// Turns follow the size of the reviewer's share; risk scores do not move
	// them, since they predicted review outcomes worse than chance.
	calm := Build(context.Background(), []File{file("a/big.go", 55_000)}, "task", &fakeClassifier{}, Options{})
	hot := Build(context.Background(), []File{file("a/big.go", 55_000)}, "task", &fakeClassifier{}, Options{})
	if calm.Turns != baseTurns+55_000/charsPerTurn || hot.Turns != calm.Turns {
		t.Fatalf("turns calm=%d hot=%d", calm.Turns, hot.Turns)
	}
	// A patch larger than a shard is truncated, so turns follow the shard size.
	if capped := Build(context.Background(), []File{file("a/huge.go", 400_000)}, "task", nil, Options{}); capped.Turns != baseTurns+defaultShardChars/charsPerTurn || capped.Turns > maxTurns {
		t.Fatalf("turns = %d", capped.Turns)
	}
}

func TestPackGroupsDirectoriesAndShards(t *testing.T) {
	files := []File{file("api/a.go", 30_000), file("api/b.go", 20_000), file("web/c.ts", 30_000), file("web/d.ts", 20_000), file("cmd/e.go", 5_000)}
	plan := Build(context.Background(), files, "task", nil, Options{ShardChars: 60_000})
	// Directories stay together; a small directory joins a shard with room.
	if len(plan.Shards) != 2 || paths(plan.Shards[0]) != "api/a.go,api/b.go" || paths(plan.Shards[1]) != "web/c.ts,web/d.ts,cmd/e.go" {
		t.Fatalf("shards = %d: %s | %s", len(plan.Shards), paths(plan.Shards[0]), paths(plan.Shards[len(plan.Shards)-1]))
	}
	spec := plan.Spec(1)
	if !strings.Contains(spec, "part 2 of 2") || strings.Contains(spec, "diff --git a/api/a.go") || !strings.Contains(spec, "diff --git a/web/c.ts") {
		t.Fatalf("shard spec wrong")
	}
}

func paths(s Shard) string {
	var out []string
	for _, f := range s.Files {
		out = append(out, f.Path)
	}
	return strings.Join(out, ",")
}

func TestPackTruncatesOversizedPatches(t *testing.T) {
	plan := Build(context.Background(), []File{file("big.go", 90_000)}, "task", nil, Options{ShardChars: 60_000})
	s := plan.Shards[0]
	if len(s.Truncated) != 1 || len(s.Files[0].Patch) > 61_000 || !strings.Contains(plan.Spec(0), "TRUNCATED PATCHES") {
		t.Fatalf("shard = %d chars, truncated %v", len(s.Files[0].Patch), s.Truncated)
	}
}

func TestPackSummarisesLowPriorityFilesOverBudget(t *testing.T) {
	c := &fakeClassifier{needs: map[string]float64{"a/doc.md": 0.4, "b/doc.md": 0.9, "c/doc.md": 0.5}}
	files := []File{file("a/doc.md", 50_000), file("b/doc.md", 50_000), file("c/doc.md", 50_000), file("d/main.go", 50_000)}
	plan := Build(context.Background(), files, "task", c, Options{ShardChars: 60_000, MaxShards: 2})
	if len(plan.Shards) != 2 {
		t.Fatalf("shards = %d", len(plan.Shards))
	}
	if decision(plan, "a/doc.md").Included || decision(plan, "c/doc.md").Included || !decision(plan, "b/doc.md").Included || !decision(plan, "d/main.go").Included {
		t.Fatalf("decisions = %+v", plan.Decisions)
	}
	if !strings.Contains(decision(plan, "a/doc.md").Reason, "reviewer budget") {
		t.Fatalf("reason = %q", decision(plan, "a/doc.md").Reason)
	}
}

func TestPackNeverDropsCode(t *testing.T) {
	var files []File
	for i := range 6 {
		files = append(files, file(fmt.Sprintf("d%d/main.go", i), 50_000))
	}
	plan := Build(context.Background(), files, "task", nil, Options{ShardChars: 60_000, MaxShards: 2})
	if len(plan.Shards) != 2 {
		t.Fatalf("shards = %d", len(plan.Shards))
	}
	total := 0
	for _, s := range plan.Shards {
		total += len(s.Files)
	}
	if total != 6 || len(plan.Shards[1].Truncated) == 0 {
		t.Fatalf("every code file must stay in the review: %d files, truncated %v", total, plan.Shards[1].Truncated)
	}
}

func TestMerge(t *testing.T) {
	single := Plan{Shards: []Shard{{}}}
	if out := Merge(single, []Verdict{{Conclusive: true, Pass: true}}); !out.Pass || out.Inconclusive {
		t.Fatalf("out = %+v", out)
	}
	if out := Merge(single, []Verdict{{Conclusive: true, Findings: []string{"nil deref"}}}); out.Pass || out.Findings[0] != "nil deref" {
		t.Fatalf("out = %+v", out)
	}
	multi := Plan{Shards: []Shard{{}, {}, {}}}
	out := Merge(multi, []Verdict{{Shard: 0, Conclusive: true, Pass: true}, {Shard: 1, Conclusive: true, Findings: []string{"race"}}, {Shard: 2, Accepted: "part 3 accepted"}})
	if out.Pass || out.Inconclusive || out.Findings[0] != "[part 2] race" || out.Notes[0] != "part 3 accepted" {
		t.Fatalf("out = %+v", out)
	}
	if out := Merge(multi, []Verdict{{Shard: 0, Conclusive: true, Pass: true}, {Shard: 1}}); out.Pass || !out.Inconclusive {
		t.Fatalf("a shard without a verdict makes the review inconclusive: %+v", out)
	}
}

func TestJevClassifierAsksOneQuestionPerItem(t *testing.T) {
	var calls atomic.Int32
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls.Add(1)
		var req struct {
			State     map[string]any             `json:"state"`
			Questions map[string]json.RawMessage `json:"questions"`
		}
		_ = json.NewDecoder(r.Body).Decode(&req)
		answers := map[string]any{}
		for name := range req.Questions {
			p := 0.2
			if req.State["file"] == "ci.yaml" || strings.Contains(fmt.Sprint(req.State["finding"]), "race") {
				p = 0.9
			}
			answers[name] = map[string]any{"type": "noul", "noul": p}
			if name == "risk" {
				answers[name] = map[string]any{"type": "score", "score": 1.0, "legend": map[string]string{"0": "l", "1": "m", "2": "h"}}
			}
		}
		_ = json.NewEncoder(w).Encode(map[string]any{"model": "jev-1.13.0", "answers": answers})
	}))
	defer srv.Close()
	c := JevClassifier{Client: jev.New("k", srv.URL, "", time.Second)}
	ctx := context.Background()
	scores, err := c.NeedsReview(ctx, "task", []File{{Path: "README.md"}, {Path: "ci.yaml"}})
	if err != nil || scores[0] != 0.2 || scores[1] != 0.9 {
		t.Fatalf("needs review = %v %v", scores, err)
	}
	if calls.Load() != 2 {
		t.Fatalf("calls = %d, want one per item", calls.Load())
	}
}

func TestJevClassifierFailsTheWholeBatch(t *testing.T) {
	var n atomic.Int32
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		if n.Add(1) == 2 {
			w.WriteHeader(529)
			return
		}
		_ = json.NewEncoder(w).Encode(map[string]any{"answers": map[string]any{"needs_review": map[string]any{"type": "noul", "noul": 0.5}}})
	}))
	defer srv.Close()
	c := JevClassifier{Client: jev.New("k", srv.URL, "", time.Second)}
	if _, err := c.NeedsReview(context.Background(), "t", []File{{Path: "a"}, {Path: "b"}, {Path: "c"}}); err == nil {
		t.Fatal("one failed call must fail the batch rather than score the file zero")
	}
}

func TestCascadeSizeAndTestRules(t *testing.T) {
	small := []File{{Path: "a.go", Added: 10, Removed: 2, Class: Code}, {Path: "go.sum", Added: 900, Class: Lockfile}}
	if Large(small) {
		t.Fatal("lockfile churn must not make a change large")
	}
	if !Large([]File{{Path: "a.go", Added: CascadeMaxLines + 1, Class: Code}}) {
		t.Fatal("a change over the line limit is large")
	}
	cases := map[string]bool{
		"pkg/a_test.go":         true,
		"tests/test_api.py":     true,
		"web/app.spec.ts":       true,
		"pkg/a.go":              false,
		"docs/testing-guide.md": false,
	}
	for p, want := range cases {
		if got := TouchesTests([]File{{Path: p, Removed: 1}}); got != want {
			t.Errorf("%s: got %v, want %v", p, got, want)
		}
	}
	if TouchesTests([]File{{Path: "pkg/a_test.go", Added: 5}}) {
		t.Fatal("only adding tests does not need a reviewer's judgement")
	}
}
